apiVersion: v1
kind: Service
metadata:
  name: formularios-unificados-admin
  labels:
    app: formularios-unificados-admin
spec:
  selector:
    app: formularios-unificados-admin
  ports:
    - name: http
      port: 80
      targetPort: 3000
