apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dcor-formularios-unificados-cnj

resources:
  - ../../base

images:
  - name: registry.cnj.jus.br/dcor/formularios-unificados-admin
    newName: registry.cnj.jus.br/dcor/formularios-unificados-admin
    newTag: latest
